# Generated by Django 5.2.6 on 2026-05-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='booking_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
