# Generated by Django 5.2.6 on 2026-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional real image URL'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='activities/'),
        ),
    ]
