# Generated by Django 5.2.6 on 2026-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activityimage_external_url_alter_activityimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='affiliate_label',
            field=models.CharField(blank=True, default='Xem ưu đãi liên kết', max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Optional partner/affiliate booking URL'),
        ),
        migrations.AddField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, TikTok or Facebook video URL'),
        ),
    ]
