# Generated by Django 5.2.6 on 2025-09-26 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("color_code", models.CharField(default="#000000", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "min_spending",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum annual spending to achieve/maintain this tier",
                        max_digits=10,
                    ),
                ),
                (
                    "min_flights",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum annual flights to achieve/maintain this tier",
                    ),
                ),
                (
                    "min_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum points required to achieve this tier",
                    ),
                ),
                (
                    "points_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Points earning multiplier (e.g., 1.5 = 50% bonus)",
                        max_digits=3,
                    ),
                ),
                ("priority_boarding", models.BooleanField(default=False)),
                (
                    "free_baggage_allowance",
                    models.PositiveIntegerField(
                        default=0, help_text="Additional free baggage allowance in kg"
                    ),
                ),
                ("lounge_access", models.BooleanField(default=False)),
                ("free_seat_selection", models.BooleanField(default=False)),
                (
                    "upgrade_priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Priority for automatic upgrades (higher = better priority)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Tier hierarchy order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loyalty Tier",
                "verbose_name_plural": "Loyalty Tiers",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("points_multiplier", "Points Multiplier"),
                            ("bonus_points", "Bonus Points"),
                            ("tier_bonus", "Tier Bonus"),
                            ("spending_bonus", "Spending Bonus"),
                            ("double_points", "Double Points"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Points multiplier (e.g., 2.0 for double points)",
                        max_digits=3,
                    ),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Fixed bonus points to award"
                    ),
                ),
                (
                    "minimum_spending",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum spending to qualify",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "max_uses_per_member",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum times a member can benefit from this promotion",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eligible_tiers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty for all tiers",
                        to="loyalty.loyaltytier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Promotion",
                "verbose_name_plural": "Loyalty Promotions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=20, unique=True)),
                ("points_balance", models.PositiveIntegerField(default=0)),
                ("lifetime_points", models.PositiveIntegerField(default=0)),
                (
                    "annual_spending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("annual_flights", models.PositiveIntegerField(default=0)),
                ("annual_points_earned", models.PositiveIntegerField(default=0)),
                ("tier_achieved_date", models.DateTimeField(auto_now_add=True)),
                ("tier_expires_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateTimeField(auto_now_add=True)),
                ("last_activity_date", models.DateTimeField(auto_now=True)),
                ("tracking_year", models.PositiveIntegerField(default=2024)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_members",
                        to="loyalty.loyaltytier",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="loyalty.loyaltytier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Membership",
                "verbose_name_plural": "Loyalty Memberships",
                "ordering": ["-tier__order", "-points_balance"],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earning", "Points Earned"),
                            ("redemption", "Points Redeemed"),
                            ("expiry", "Points Expired"),
                            ("adjustment", "Manual Adjustment"),
                            ("bonus", "Bonus Points"),
                            ("tier_upgrade", "Tier Upgrade"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive for earning, negative for spending"
                    ),
                ),
                ("balance_after", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=255)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Booking reference, order ID, etc.",
                        max_length=50,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who created manual adjustments",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to="loyalty.loyaltymembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Points Transaction",
                "verbose_name_plural": "Points Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("flight", "Flight Rewards"),
                            ("upgrade", "Cabin Upgrades"),
                            ("service", "Service Rewards"),
                            ("merchandise", "Merchandise"),
                            ("partner", "Partner Rewards"),
                            ("experience", "Experiences"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("points_required", models.PositiveIntegerField()),
                (
                    "cash_equivalent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Equivalent cash value for reference",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave blank for unlimited", null=True
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="rewards/")),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "minimum_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimum tier required to redeem this reward",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loyalty.loyaltytier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "ordering": ["category", "order", "points_required"],
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redemption_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("points_redeemed", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(
                        blank=True,
                        help_text="Associated booking if applicable",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="loyalty.loyaltymembership",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="loyalty.reward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Redemption",
                "verbose_name_plural": "Reward Redemptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_earned", models.PositiveIntegerField(default=0)),
                (
                    "spending_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("booking_reference", models.CharField(blank=True, max_length=10)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_usages",
                        to="loyalty.loyaltymembership",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="loyalty.loyaltypromotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Usage",
                "verbose_name_plural": "Promotion Usages",
                "ordering": ["-used_at"],
                "unique_together": {("promotion", "membership", "booking_reference")},
            },
        ),
    ]
