# Generated by Django 5.2.6 on 2025-09-26 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(fields=["user"], name="loyalty_loy_user_id_ffd666_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["member_id"], name="loyalty_loy_member__c668b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(fields=["tier"], name="loyalty_loy_tier_id_3d11a1_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["points_balance"], name="loyalty_loy_points__02d708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["is_active"], name="loyalty_loy_is_acti_9d8141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["tier", "points_balance"], name="loyalty_loy_tier_id_aad31d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["is_active", "tier"], name="loyalty_loy_is_acti_e696b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["last_activity_date"], name="loyalty_loy_last_ac_041de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltymembership",
            index=models.Index(
                fields=["tracking_year"], name="loyalty_loy_trackin_88963c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltytier",
            index=models.Index(fields=["order"], name="loyalty_loy_order_f9fb78_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltytier",
            index=models.Index(
                fields=["min_points"], name="loyalty_loy_min_poi_8ce139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltytier",
            index=models.Index(
                fields=["is_active"], name="loyalty_loy_is_acti_4ab5fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltytier",
            index=models.Index(
                fields=["is_active", "order"], name="loyalty_loy_is_acti_5634d1_idx"
            ),
        ),
    ]
