# Generated by Django 4.2.7 on 2025-09-27 08:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "0002_flightsearch_created_at_flightsearch_is_saved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0001_initial"),
        ("hotels", "0004_hotel_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("honeymoon", "Honeymoon"),
                            ("family", "Family"),
                            ("adventure", "Adventure"),
                            ("cultural", "Cultural"),
                            ("business", "Business"),
                            ("luxury", "Luxury"),
                            ("budget", "Budget"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=500)),
                ("destination_city", models.CharField(max_length=100)),
                ("destination_country", models.CharField(max_length=100)),
                ("duration_days", models.PositiveIntegerField()),
                ("duration_nights", models.PositiveIntegerField()),
                (
                    "base_price_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "single_supplement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("includes_flight", models.BooleanField(default=True)),
                ("includes_hotel", models.BooleanField(default=True)),
                ("includes_meals", models.BooleanField(default=False)),
                ("includes_activities", models.BooleanField(default=False)),
                ("includes_transport", models.BooleanField(default=False)),
                ("includes_insurance", models.BooleanField(default=False)),
                ("min_participants", models.PositiveIntegerField(default=1)),
                ("max_participants", models.PositiveIntegerField(default=20)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-featured", "title"],
            },
        ),
        migrations.CreateModel(
            name="PackageComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("activity", "Activity"),
                            ("transport", "Transport"),
                            ("meal", "Meal"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("day_number", models.PositiveIntegerField()),
                ("duration", models.CharField(blank=True, max_length=100)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("is_included", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activities.activity",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flights.flight",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotels.hotel",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="packages.travelpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="PackageBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                ("adults", models.PositiveIntegerField(default=1)),
                ("children", models.PositiveIntegerField(default=0)),
                ("infants", models.PositiveIntegerField(default=0)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_services_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("special_requests", models.TextField(blank=True)),
                ("dietary_requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="packages.travelpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
