# Generated by Django 5.2.6 on 2025-09-26 14:12

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("internet", "Internet"),
                            ("parking", "Parking"),
                            ("transportation", "Transportation"),
                            ("services", "Services"),
                            ("business", "Business"),
                            ("wellness", "Wellness & Fitness"),
                            ("food_drink", "Food & Drink"),
                            ("entertainment", "Entertainment"),
                            ("family", "Family"),
                            ("accessibility", "Accessibility"),
                            ("safety", "Safety & Security"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("flag_url", models.URLField(blank=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HotelChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="hotel_chains/"),
                ),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cities/"),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="hotels.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
                "unique_together": {("name", "country")},
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "star_rating",
                    models.PositiveIntegerField(
                        help_text="Hotel star rating (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("check_in_time", models.TimeField(default="15:00")),
                ("check_out_time", models.TimeField(default="11:00")),
                ("cancellation_policy", models.TextField(blank=True)),
                ("child_policy", models.TextField(blank=True)),
                ("pet_policy", models.TextField(blank=True)),
                (
                    "price_from",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting price per night",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("total_rooms", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amenities", models.ManyToManyField(blank=True, to="hotels.amenity")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="hotels.city",
                    ),
                ),
                (
                    "hotel_chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotels.hotelchain",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-average_rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="HotelFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dining", "Dining"),
                            ("recreation", "Recreation"),
                            ("business", "Business"),
                            ("wellness", "Wellness"),
                            ("connectivity", "Connectivity"),
                            ("transportation", "Transportation"),
                            ("services", "Services"),
                            ("accessibility", "Accessibility"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_free", models.BooleanField(default=True)),
                (
                    "additional_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost if not free",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("operating_hours", models.CharField(blank=True, max_length=100)),
                ("is_24_hours", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotels/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior"),
                            ("lobby", "Lobby"),
                            ("room", "Room"),
                            ("bathroom", "Bathroom"),
                            ("restaurant", "Restaurant"),
                            ("pool", "Pool"),
                            ("gym", "Gym/Fitness"),
                            ("spa", "Spa"),
                            ("meeting", "Meeting Room"),
                            ("amenity", "Amenity"),
                            ("view", "View"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=150)),
                ("description", models.TextField()),
                (
                    "size_sqm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Room size in square meters", null=True
                    ),
                ),
                ("max_occupancy", models.PositiveIntegerField(default=2)),
                ("max_adults", models.PositiveIntegerField(default=2)),
                ("max_children", models.PositiveIntegerField(default=0)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Bed"),
                            ("twin", "Twin Beds"),
                            ("double", "Double Bed"),
                            ("queen", "Queen Bed"),
                            ("king", "King Bed"),
                            ("sofa", "Sofa Bed"),
                            ("bunk", "Bunk Bed"),
                            ("murphy", "Murphy Bed"),
                        ],
                        default="double",
                        max_length=50,
                    ),
                ),
                ("number_of_beds", models.PositiveIntegerField(default=1)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_refundable", models.BooleanField(default=True)),
                (
                    "free_cancellation_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours before check-in for free cancellation",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_rooms", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amenities", models.ManyToManyField(blank=True, to="hotels.amenity")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["base_price"],
                "unique_together": {("hotel", "slug")},
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rooms/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="RoomAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("available_rooms", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_holiday", models.BooleanField(default=False)),
                (
                    "demand_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="hotels.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("room_type", "date")},
            },
        ),
    ]
