# Generated by Django 5.2.6 on 2025-09-26 14:43

from django.db import migrations
from django.utils.text import slugify


def populate_hotel_slugs(apps, schema_editor):
    Hotel = apps.get_model('hotels', 'Hotel')
    for hotel in Hotel.objects.filter(slug=''):
        hotel.slug = slugify(f"{hotel.name}-{hotel.city.name}")
        hotel.save()

def reverse_populate_hotel_slugs(apps, schema_editor):
    # This is irreversible, but we can set slugs to empty
    Hotel = apps.get_model('hotels', 'Hotel')
    Hotel.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_hotel_slugs, reverse_populate_hotel_slugs),
    ]
