# Generated by Django 4.2.7 on 2025-09-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image_url",
            field=models.URLField(blank=True, help_text="Primary hotel image URL"),
        ),
    ]
