# Generated by Django 5.2.6 on 2026-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional real image URL'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional real room image URL'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
    ]
