# Generated by Django 5.2.6 on 2026-05-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_itinerary_itinerarystop'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystop',
            name='cost_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
