# Generated by Django 5.2.6 on 2026-05-25 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_itinerarystop_cost_note_itinerarystop_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='activity_type',
            field=models.CharField(choices=[('attraction', 'Attraction'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('food', 'Food')], default='attraction', max_length=20),
        ),
    ]
