# Generated by Django 5.2.6 on 2026-05-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_itinerary_created_by_itinerarystop_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
    ]
