# Generated by Django 5.2.6 on 2026-05-28 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotel_currency_alter_hotelreservation_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Cho thanh toan'), ('completed', 'Da thanh toan'), ('cancelled', 'Da huy'), ('refunded', 'Da hoan tien')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Cho xac nhan'), ('confirmed', 'Da xac nhan'), ('completed', 'Hoan tat'), ('cancelled', 'Da huy')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hotels.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('booking_type', models.CharField(max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotels.itineraryorder')),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='itineraryorder',
            index=models.Index(fields=['order_code'], name='hotels_itin_order_c_ab276d_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryorder',
            index=models.Index(fields=['user', 'status'], name='hotels_itin_user_id_c774ad_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryorder',
            index=models.Index(fields=['payment_status', 'created_at'], name='hotels_itin_payment_dbe789_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryorderitem',
            index=models.Index(fields=['booking_type', 'object_id'], name='hotels_itin_booking_1ae9e9_idx'),
        ),
    ]
