# Generated by Django 5.2.6 on 2026-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_itineraryorder_itineraryorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('completed', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='itineraryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
