# Generated by Django 5.2.6 on 2025-09-26 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("iso_code", models.CharField(max_length=2, unique=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("variant", models.CharField(blank=True, max_length=50)),
                ("total_seats", models.PositiveIntegerField()),
                ("economy_seats", models.PositiveIntegerField()),
                ("premium_economy_seats", models.PositiveIntegerField(default=0)),
                ("business_seats", models.PositiveIntegerField(default=0)),
                ("first_class_seats", models.PositiveIntegerField(default=0)),
                ("max_range_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cruise_speed_kmh",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "wingspan_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_entertainment", models.BooleanField(default=False)),
                ("has_power_outlets", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["manufacturer", "model"],
                "unique_together": {("manufacturer", "model", "variant")},
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("iata_code", models.CharField(max_length=3, unique=True)),
                ("icao_code", models.CharField(blank=True, max_length=4, unique=True)),
                ("city", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("timezone", models.CharField(max_length=50)),
                ("elevation_ft", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_international", models.BooleanField(default=False)),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airports",
                        to="flights.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iata_code", models.CharField(blank=True, max_length=2, unique=True)),
                ("icao_code", models.CharField(blank=True, max_length=3, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="airlines/"),
                ),
                ("website", models.URLField(blank=True)),
                ("baggage_policy", models.TextField(blank=True)),
                ("cancellation_policy", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_low_cost", models.BooleanField(default=False)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flights.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("adults", models.PositiveIntegerField(default=1)),
                ("children", models.PositiveIntegerField(default=0)),
                ("infants", models.PositiveIntegerField(default=0)),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business"),
                            ("first_class", "First Class"),
                        ],
                        default="economy",
                        max_length=20,
                    ),
                ),
                ("search_timestamp", models.DateTimeField(auto_now_add=True)),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches_to",
                        to="flights.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches_from",
                        to="flights.airport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.PositiveIntegerField()),
                ("typical_duration_minutes", models.PositiveIntegerField()),
                ("is_popular", models.BooleanField(default=False)),
                ("is_domestic", models.BooleanField(default=False)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="flights.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="flights.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["origin__name", "destination__name"],
                "unique_together": {("origin", "destination")},
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("departure_terminal", models.CharField(blank=True, max_length=5)),
                ("arrival_terminal", models.CharField(blank=True, max_length=5)),
                ("departure_gate", models.CharField(blank=True, max_length=10)),
                ("arrival_gate", models.CharField(blank=True, max_length=10)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("distance_km", models.PositiveIntegerField()),
                ("stops", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("delayed", "Delayed"),
                            ("boarding", "Boarding"),
                            ("departed", "Departed"),
                            ("arrived", "Arrived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("economy_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "premium_economy_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "business_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "first_class_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("economy_available", models.PositiveIntegerField()),
                ("premium_economy_available", models.PositiveIntegerField(default=0)),
                ("business_available", models.PositiveIntegerField(default=0)),
                ("first_class_available", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="flights.aircraft",
                    ),
                ),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="flights.airline",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arriving_flights",
                        to="flights.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departing_flights",
                        to="flights.airport",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="flights.route",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_time"],
                "unique_together": {("airline", "flight_number", "departure_time")},
            },
        ),
        migrations.CreateModel(
            name="BaggageAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fare_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Economy"),
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business"),
                            ("first_class", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                ("carryon_pieces", models.PositiveIntegerField(default=1)),
                ("carryon_weight_kg", models.PositiveIntegerField(default=7)),
                ("carryon_dimensions", models.CharField(blank=True, max_length=50)),
                ("checked_pieces_included", models.PositiveIntegerField(default=0)),
                ("checked_weight_kg", models.PositiveIntegerField(default=23)),
                ("checked_dimensions", models.CharField(blank=True, max_length=50)),
                (
                    "extra_bag_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "overweight_fee_per_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baggage_allowances",
                        to="flights.airline",
                    ),
                ),
            ],
            options={
                "unique_together": {("airline", "fare_type")},
            },
        ),
        migrations.CreateModel(
            name="FlightSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=5)),
                ("row", models.PositiveIntegerField()),
                ("seat_letter", models.CharField(max_length=1)),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business"),
                            ("first_class", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("window", "Window"),
                            ("middle", "Middle"),
                            ("aisle", "Aisle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_exit_row", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("has_extra_legroom", models.BooleanField(default=False)),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="flights.flight",
                    ),
                ),
            ],
            options={
                "ordering": ["row", "seat_letter"],
                "unique_together": {("flight", "seat_number")},
            },
        ),
        migrations.CreateModel(
            name="SavedFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business"),
                            ("first_class", "First Class"),
                        ],
                        default="economy",
                        max_length=20,
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="flights.flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_flights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("user", "flight", "cabin_class")},
            },
        ),
    ]
