# Generated by Django 5.2.6 on 2025-09-26 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsearch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flightsearch",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flightsearch",
            name="passengers",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="flightsearch",
            name="search_name",
            field=models.CharField(
                blank=True, help_text="Name for saved searches", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="flightsearch",
            name="trip_type",
            field=models.CharField(
                choices=[
                    ("one_way", "One Way"),
                    ("round_trip", "Round Trip"),
                    ("multi_city", "Multi City"),
                ],
                default="one_way",
                max_length=20,
            ),
        ),
    ]
