# Generated by Django 5.2.6 on 2026-05-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flightsearch_created_at_flightsearch_is_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
    ]
