# Generated by Django 5.2.6 on 2025-09-26 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "0002_flightsearch_created_at_flightsearch_is_saved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium Economy"),
                            ("business", "Business"),
                            ("first_class", "First Class"),
                        ],
                        default="economy",
                        max_length=20,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taxes_and_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skipped", "Payment Skipped (Testing)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Meal preferences, accessibility needs, etc.",
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="flights.flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("skipped", "Payment Skipped (Testing)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("card_last_four", models.CharField(blank=True, max_length=4)),
                ("card_type", models.CharField(blank=True, max_length=20)),
                ("payment_gateway", models.CharField(blank=True, max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("gateway_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("skipped", "Skipped (Testing)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("ms", "Ms."),
                            ("dr", "Dr."),
                            ("prof", "Prof."),
                            ("child", "Child"),
                            ("infant", "Infant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "passenger_type",
                    models.CharField(
                        choices=[
                            ("adult", "Adult (12+ years)"),
                            ("child", "Child (2-11 years)"),
                            ("infant", "Infant (under 2 years)"),
                        ],
                        default="adult",
                        max_length=10,
                    ),
                ),
                ("passport_number", models.CharField(blank=True, max_length=20)),
                (
                    "passport_country",
                    models.CharField(
                        blank=True, help_text="ISO country code", max_length=2
                    ),
                ),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "meal_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No Preference"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("kosher", "Kosher"),
                            ("halal", "Halal"),
                            ("gluten_free", "Gluten Free"),
                            ("diabetic", "Diabetic"),
                            ("child_meal", "Child Meal"),
                            ("baby_meal", "Baby Meal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "seat_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No Preference"),
                            ("window", "Window"),
                            ("aisle", "Aisle"),
                            ("middle", "Middle"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "special_assistance",
                    models.TextField(
                        blank=True,
                        help_text="Wheelchair, visual/hearing assistance, etc.",
                    ),
                ),
                (
                    "assigned_seat",
                    models.CharField(blank=True, help_text="e.g., 12A", max_length=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["passenger_type", "last_name", "first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_reference"], name="bookings_bo_booking_8a7545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="bookings_bo_user_id_69a5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["flight", "status"], name="bookings_bo_flight__45560d_idx"
            ),
        ),
    ]
