# Generated by Django 5.2.6 on 2026-05-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_passenger_date_of_birth'),
        ('flights', '0002_flightsearch_created_at_flightsearch_is_saved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_order', models.PositiveIntegerField(default=1)),
                ('cabin_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first_class', 'First Class')], default='economy', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_segments', to='bookings.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_segments', to='flights.flight')),
            ],
            options={
                'ordering': ['segment_order'],
                'indexes': [models.Index(fields=['booking', 'segment_order'], name='bookings_bo_booking_40b4a5_idx'), models.Index(fields=['flight'], name='bookings_bo_flight__127386_idx')],
                'unique_together': {('booking', 'segment_order')},
            },
        ),
    ]
