# Generated by Django 5.2.6 on 2026-05-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingflight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
    ]
