# Generated by Django 5.2.6 on 2026-05-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('train', 'Tau hoa'), ('bus', 'Xe khach')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(choices=[('train_station', 'Ga tau'), ('bus_station', 'Ben xe / diem don')], max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('train', 'Tau hoa'), ('bus', 'Xe khach')], max_length=20)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('typical_duration_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='transport.transportstation')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='transport.transportstation')),
            ],
            options={
                'ordering': ['transport_type', 'origin__city', 'destination__city'],
                'unique_together': {('transport_type', 'origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='TransportTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(max_length=30)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('seat_class', models.CharField(choices=[('standard', 'Pho thong'), ('sleeper', 'Giuong nam'), ('vip', 'Limousine/VIP'), ('soft_seat', 'Ghe mem'), ('soft_sleeper', 'Giuong nam mem')], max_length=30)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('pickup_note', models.CharField(blank=True, max_length=255)),
                ('dropoff_note', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField(default=20)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('status', models.CharField(choices=[('scheduled', 'Dang mo ban'), ('sold_out', 'Het cho'), ('cancelled', 'Da huy')], default='scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.transportprovider')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.transportroute')),
            ],
            options={
                'ordering': ['departure_time'],
                'unique_together': {('provider', 'trip_code', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=10, unique=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=254)),
                ('special_requests', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Cho xac nhan'), ('confirmed', 'Da xac nhan'), ('cancelled', 'Da huy')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'The tin dung / ghi no'), ('bank_transfer', 'Chuyen khoan ngan hang'), ('cash', 'Thanh toan khi nhan ve'), ('skipped', 'Thanh toan demo')], max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_bookings', to=settings.AUTH_USER_MODEL)),
                ('dropoff_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='transport.transportstation')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='transport.transportstation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.transporttrip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_reference'], name='transport_t_booking_361450_idx'), models.Index(fields=['user', 'status'], name='transport_t_user_id_364d87_idx')],
            },
        ),
    ]
